name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - openjdk
  - numpy
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - tika
    - jupyter-offlinenotebook